apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-api-config
  namespace: devops-api
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PROMETHEUS_SCRAPE_ENABLED: "true"
  METRICS_PORT: "3000"
